---

- name: Firewalld enable coturn standard ports
  ansible.posix.firewalld:
    port: "{{ item.port }}/{{ item.proto }}"
    permanent: yes
    state: enabled
  loop:
    - port: "{{ coturn_listening_port }}"
      proto: tcp
    - port: "{{ coturn_listening_port }}"
      proto: udp
    - port: "{{ coturn_min_port }}-{{ coturn_max_port }}"
      proto: udp
  notify: restart coturn

- name: Firewalld enable coturn tls ports and certificate renewal
  ansible.posix.firewalld:
    port: item
    permanent: yes
    state: enabled
  loop:
    - "{{ coturn_tls_listening_port }}/tcp"
    - "{{ coturn_tls_listening_port }}/udp"
    - "80/tcp"
  when: coturn_use_tls
  notify: restart coturn
