---

- name: install coturn
  apt:
    pkg: coturn
    state: latest

- name: Give coturn access to TLS cert
  user:
    name: turnserver
    groups: "{{ coturn_tls_group }}"
    append: true
  when: coturn_tls and coturn_tls_group is defined

- name: Grant user Turnserver read execute access to /etc/letsencrypt/
  acl:
    path: /etc/letsencrypt/
    entity: turnserver
    etype: user
    permissions: rx
    recursive: yes
    state: present

- name: Create systemd override for coturn
  block:
    - name: Create needed folder
      file:
        path: /etc/systemd/system/coturn.service.d/
        state: directory
        mode: '0755'
    - name: Apply coturn override template
      template:
        src: override.conf
        dest: /etc/systemd/system/coturn.service.d/override.conf
        owner: root
        group: root
        mode: '0644'

- name: Create lograte structure
  block:
    - name: Create needed folder
      file:
        path: /var/log/turnserver
        owner: turnserver
        group: turnserver
        state: directory
        mode: '0755'
    - name: Template logrotate
      template:
        src: logging.conf
        dest: /etc/logrotate.d/coturn
        owner: root
        group: root
        mode: '0644'

- name: Set cap_net_bind_service=+ep on /usr/bin/turnserver
  capabilities:
    path: /usr/bin/turnserver
    capability: cap_net_bind_service=+ep
    state: present

- name: ensure coturn is enabled
  lineinfile:
    dest: /etc/default/coturn
    line: TURNSERVER_ENABLED=1
    regexp: "^#?TURNSERVER_ENABLED="

- name: Create parameters for Diffie–Hellman (could take a while)
  command: "openssl dhparam -out /etc/coturn-dh-{{ coturn_dhparam_length }}.pem {{ coturn_dhparam_length }}"
  args:
    creates: /etc/coturn-dh-{{ coturn_dhparam_length }}.pem
  when: coturn_tls
  notify: restart coturn

- name: configure coturn
  template:
    dest: /etc/turnserver.conf
    src: turnserver.conf.j2
    owner: root
    group: root
    mode: 0644
  notify: restart coturn
