---

- name: Install dependencies
  ansible.legacy.apt:
    update_cache: true
    name: ufw

- name: UFW allow known services
  community.general.ufw:
    rule: allow
    name: OpenSSH

- name: UFW allow coturn standard ports
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  loop:
    - port: "{{ coturn_listening_port }}"
      proto: tcp
    - port: "{{ coturn_listening_port }}"
      proto: udp
    - port: "{{ coturn_min_port }}:{{ coturn_max_port }}"
      proto: udp
  notify: restart coturn

- name: UFW allow coturn tls port and certificate renewal
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  loop:
    - port: "{{ coturn_tls_listening_port }}"
      proto: tcp
    - port: "{{ coturn_tls_listening_port }}"
      proto: udp
    - port: 80
      proto: tcp
  when: coturn_use_tls
  notify: restart coturn

- name: Enable firewall
  community.general.ufw:
    state: enabled
    policy: reject
    logging: off
